### ISSUE TITLE
LinkPlugin links wrong behaviour

### ISSUE THREAD

**Issue by SergeyOkishev** [vacenz/last-draft-js-plugins#3]
Hello, found a bug that adding a link to inline text would result updating entity, but href on link would be same as text. 
For example decorating text "github.com" with "google.com" link would result link to github.com, which seems like a wrong behaviour.

**Comment by StevenIseki** [comment]
All fixed now in version 1.2.2 of the link plugin 
Check out https://github.com/vacenz/last-draft-example-v3 for an example of use.

Sorry I didn't get to use your pr, I had a lot of work to do updating to the latest version of draft-js-plugins and draft/react so this was too out of date for me to rebase. Thanks a lot for picking it up and your work, made it east for me 👍
